[package]
name        = "wg-core"
description = "Sans-io, no_std, allocation-free WireGuard protocol core"
readme      = "README.md"
keywords    = ["wireguard", "vpn", "no-std", "embedded", "sans-io"]
categories  = ["network-programming", "no-std", "cryptography"]

edition.workspace      = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[dependencies]
blake2.workspace           = true
chacha20poly1305.workspace = true
heapless.workspace         = true
hmac.workspace             = true
subtle.workspace           = true
x25519-dalek.workspace     = true
zeroize.workspace          = true

[dev-dependencies]
hex = "0.4"
